replicaCount: 1

image:
  repository: nginxinc/nginx-unprivileged
  tag: "latest"
  pullPolicy: IfNotPresent

ports:
  - name: http
    containerPort: 80
    protocol: TCP

service:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 90
      protocol: TCP

sourceRepo:
  name: "example-app"
  url: "https://github.com/andrewdeweever/example-app"

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
