apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "example-app.fullname" . }}
  labels:
    {{- include "example-app.labels" . | nindent 4 }}
    app.kubernetes.io/source-repo: {{ .Values.sourceRepo.name | quote }}
  annotations:
    app.kubernetes.io/source-repo-url: {{ .Values.sourceRepo.url | quote }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "example-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "example-app.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/source-repo: {{ .Values.sourceRepo.name | quote }}
      annotations:
        app.kubernetes.io/source-repo-url: {{ .Values.sourceRepo.url | quote }}
    spec:
      containers:
      - name: {{ include "example-app.name" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
