apiVersion: v1
kind: Service
metadata:
  name: {{ include "example-app.fullname" . }}
  labels:
    {{- include "example-app.labels" . | nindent 4 }}
    app.kubernetes.io/source-repo: {{ .Values.sourceRepo.name | quote }}
  annotations:
    app.kubernetes.io/source-repo-url: {{ .Values.sourceRepo.url | quote }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.service.ports }}
    - port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol }}
      name: {{ .name }}
    {{- end }}
  selector:
    {{- include "example-app.selectorLabels" . | nindent 4 }}
